version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: knowlace_postgres
    restart: always
    environment:
      POSTGRES_USER: knowlace
      POSTGRES_PASSWORD: knowlace
      POSTGRES_DB: knowlace_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
